[package]
name = "mc-item-icons"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
image = "0.25.8"
rayon = "1.11.0"
serde = "1.0.225"
serde_derive = "1.0.225"
